[package]
name = "more-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zsh-module = "0.3.0"
zsh-sys = "0.1.0"
