#!/usr/bin/bash
source gitmgmt.sh --source

clone_func 'https://github.com/lbonn/rofi.git'
change_cwd

git submodule update --init --recursive

meson setup build
ninja -C build

binlink "$PWD/build/rofi"

for i in "$PWD/doc"/*.5; do
    safelink "$i" "$XDG_DATA_HOME/man/man5"
done
for i in "$PWD/doc"/*.1; do
    safelink "$i" "$XDG_DATA_HOME/man/man1"
done
