[package]
name = "battery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8.7", default-features = false, features = [
    "no-rng",
    "std",
] }
async-trait = "0.1.77"
futures = "0.3.30"
num = "0.4.1"
regex = { version = "1.10.2", features = ["use_std"] }
static_init = "1.0.3"
strum = "0.25.0"
strum_macros = "0.25.3"
tokio = { version = "1.35.1", default-features = false, features = [
    "tokio-macros",
    "macros",
    "rt",
] }
tokio-stream = "0.1.14"
zbus = { version = "3.14.1", default-features = false, features = ["tokio"] }
