#!/bin/dash
# an rcfile for the dash shell
# envirnoment variable ENV must point to this file for it to work
# this is fucking ridiculous lmao

if [ -n "${BASH_VERSION:-$ZSH_VERSION}" ] || [ -n "${DASHRC_LOADED:-}" ] || ! expr "$-" : '.*i' >/dev/null 2>&1; then
    echo "doublesourced dashrc"
    return
    exit
fi

. "$HOME/bin/vlkenv"

alias ls='ls -A --group-directories-first --color=auto'
alias q=exit
alias rm='rm -i'

PS1='$(tput sgr0; tput bold)$(r="$?";[ "$r" -ne 0 ] && echo "[$r] ")$ $(tput sgr0)'

echo loaded dashrc
DASHRC_LOADED=true
