[Service]
Environment="OLLAMA_HOME=/home/vlk/.local/share/ollama"
Environment="OLLAMA_MODELS=/home/vlk/.local/share/ollama/models"
Environment="OLLAMA_ORIGIN=*"
Environment="OLLAMA_FLASH_ATTENTION=1"
Environment="OLLAMA_MMAP=1"
