backlight_empty = ""
backlight_full = ""
backlight = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
]

bat_charging = "󰂄"
bat_discharging = "󱟤"
bat_not_available = "󰂑"
bat = [
    "󰁺",
    "󰁻",
    "󰁼",
    "󰁽",
    "󰁾",
    "󰁿",
    "󰂀",
    "󰂁",
    "󰂂",
    "󰁹",
]

bell = "󰂚"
bell-slash = "󰪑"
bluetooth = "󰂯"
calendar = "󰭧"
cogs = ""
cpu_low = "󰾆"
cpu_med = "󰾅"
cpu_high = "󰓅"
cpu_boost_on = "󰔡"
cpu_boost_off = "󰨙"
disk_drive = "󰋊"
docker = ""
github = "󰊤"
gpu = "󰢮"
headphones = "󰋋"
joystick = "󰮂"
keyboard = "󰌌"
mail = "󰾱"
memory_mem = "󰭷"
memory_swap = "󰋊"
mouse = "󰍽"
music = "󰎈"
music_next = "󰒭"
music_pause = ""
music_play = ""
music_prev = "󰒮"
net_bridge = "󱂇"
net_down = "󰇚"
net_loopback = "󰜉"
net_modem = "󰏾"
net_up = "󰕒"
net_vpn = "󰖂"
net_wired = "󰈀"
net_wireless = "󰖩"
notification = "󰂚"
phone = "󰏲"
phone_disconnected = "󰙘"
ping = "󰄨"
pomodoro = ""
pomodoro_break = "󰅶"
pomodoro_paused = ""
pomodoro_started = ""
pomodoro_stopped = "󱓻"
resolution = "󰒉"
tasks = ""
thermometer = ""
time = ""
toggle_off = "󰨙"
toggle_on = "󰔡"
unknown = "󰞋"
update = "󱧕"
uptime = "󱋡"

volume_muted = "󰝟"
volume = [
    "",
    "󰖀",
    "󰕾"
]
microphone = [
    "󰍮",
    "󰢳",
    "󰍬"
]
microphone_muted = "󰍭"
weather_clouds = ""
weather_default = ""
weather_rain = ""
weather_snow = ""
weather_sun = ""
weather_thunder = ""
xrandr = "󰍺"

# CUSTOM
gammastep_on = "󰌵"
gammastep_off = "󰌶"
