[package]
name = "vlkprompt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8.6", default-features = false, features = [
    "compile-time-rng",
    "std",
] }
git2 = { version = "0.18.1", default-features = false, optional = false }
lazy_static = "1.4.0"
zsh-module = "0.3.0"
