#!/usr/bin/zsh
# vim:ft=zsh

local information
information="$(
    printf '%s\t%s\n' \
        '󰅐 Time' "$(date +'%-m/%-d %-I:%M:%S %P')" \
        ' Term' "$TERM" \
        ' Uptime' "${$(uptime -p)#up }"
    /usr/bin/cat "$DUMBFETCH_INFO_FILE"
)"

local lsdiffed
lsdiffed="$(lsdiff)"

(
    ((COLUMNS > 55)) && vlk-window-rs \
"         _
 _______| |__
|_  / __| '_ \\
 / /\__ \ | | |
/___|___/_| |_|" \
        "$(echo -n "$information" | expand -t 10)"
    #vlk-window-rs "$(vlk-fortune-rs)"
    vlk-fortune-rs
) | lolcrab

if [ -n "$lsdiffed" ]; then
    echo -ne "\033[1m## LSDIFF ##\033[0m\n$lsdiffed"
fi

