[package]
name = "unfuckd"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
inotify = { version = "0.10.2", default-features = false }
once_cell = "1.19.0"
signal-hook = "0.3.17"
