[package]
name = "zsh-syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8.7", default-features = false, features = ["compile-time-rng", "std"] }
regex = { version = "1.10.2", features = ["use_std"] }
