[package]
name = "packapp-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# crate-type = ["rlib"]

[dependencies]
chrono = { version = "0.4.31", features = ["serde", "std", "pure-rust-locales"], default-features = false }
fuzzy-matcher = "0.3.7"
grep = { version = "0.3.1", features = ["pcre2"] }
lscolors = "0.16.0"
nu-ansi-term = { version = "0.49.0", features = ["serde"] }
rand = { version = "0.8.5", features = ["small_rng", "serde"] }
serde = "1.0.193"
size = "0.4.1"
