#!/usr/bin/bash

xrdb -merge "${XRESOURCES:-$HOME/.Xresources}"

session='i3'
export XDG_SESSION_DESKTOP='i3'

if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
    exec dbus-run-session -- "$session"
else
    exec "$session"
fi
