[package]
edition = "2024"
name = "dumbfetch2"
rust-version = "1.95"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = true

[profile.dev]
panic = "abort"

[dependencies]
arrayvec = { default-features = false, version = "0.7.6" }
itoa = "1.0.18"
libc = { default-features = false, version = "0.2.186" }
