# fit-mode: contain | cover | tile | fill
wallpaper {
    monitor = eDP-1
    path = ~/.local/share/backgrounds/vlkbg/pattern.jpg
}

wallpaper {
    monitor =
    path = ~/.local/share/backgrounds/vlkbg/alan.jpg
}

splash = false
ipc = false
# vim:ft=hyprlang
