dialect = "us"
sync_frequency = "0"
## possible values: prefix, fulltext, fuzzy
search_mode = "fuzzy"
## possible values: auto, full, compact
#style = "auto"
## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
# exit_mode = "return-original"

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
# history_filter = [
#   "^secret-cmd",
#   "^innocuous-cmd .*--secret=.+"
# ]
