[package]
name = "echoc"
version = "0.1.0"
description = "An echo command that behaves exactly as you would expect."
edition = "2021"

[profile.release]
lto = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
