#!/bin/dash
# shellcheck shell=dash
# shellcheck disable=2139,2154,1091
# vim:foldmethod=marker:ft=sh
# an rcfile for the dash shell
# envirnoment variable ENV must point to this file for it to work
# this is fucking ridiculous lmao

if [ -n "${BASH_VERSION:-$ZSH_VERSION}" ] || [ -n "${DASHRC_LOADED:-}" ] || [ "${-#*i}" = "$-" ]; then
    echo "skipping dashrc"
    return
    exit
fi

. "$HOME/bin/vlkenv"

__lscmd="$(which --skip-alias ls) --color=auto --group-directories-first"

alias ls="${LS_COMMAND:=$__lscmd -A}"
alias ll="${LL_COMMAND:=$__lscmd -Al}"
alias la="${LA_COMMAND:=$__lscmd -a}"

unset __lscmd

alias -='cd -'

alias q=exit
alias rm='rm -i'

if command -v lscolors >/dev/null 2>&1; then
    _colorhome="$(lscolors "$HOME" | sed 's|/.*|~|')"
    __wdprint() {
        # dash supports the `local` keyword for some reason
        local __trailing_slash
        [ "${PWD:=NULLPWD}" != "$HOME" ] && __trailing_slash='/'
        case "$PWD" in
        "$HOME"*)
            echo "${_colorhome}${__trailing_slash:-}$(lscolors "$PWD" | grep -oP '/[^/]*/[^/]*/\K.*')"
            ;;
        *)
            lscolors "$PWD"
            ;;
        esac
    }
else
    __wdprint() {
        case "${PWD:=NULLPWD}" in
        "$HOME"*)
            echo "$PWD" | sed "s|${HOME}|~|"
            ;;
        *)
            echo "$PWD"
            ;;
        esac
    }
fi

PS1='$(
    r="$?"
    i="$(__wdprint) \$"
    [ "$r" -ne 0 ] && i="[$r] $i"
    tput sgr0 ; tput bold
    echo -n "$i "
    tput sgr0
)'

echo loaded dashrc
DASHRC_LOADED=true
