#!/usr/bin/env bash

echo "$1 $2 $3"
TYPE="$1"
DEVICE="$2"
STATUS="$3"
shift 3
DESC="$*"

xinputfile="$XDG_RUNTIME_DIR/xinput-old"
_normalize_pointer() {
    local my_xinput="$(xinput)"
    [ ! -f "$xinputfile" ] && echo "$my_xinput" >"$xinputfile"
    if ! diff -q "$xinputfile" <(echo "$my_xinput"); then
        pointer.sh -n
        echo "$my_xinput" >"$xinputfile"
    fi
}

if [[ "$STATUS" == "connected" ]]; then
    echo "xplug detected $TYPE"
    case "$TYPE" in
    display)
        # xlayoutdisplay --quiet
        # vlk-xrandr.sh
        # vlkbg.sh
        ;;
    pointer)
        _normalize_pointer
        ;;
    esac
else
    case "$TYPE" in
    display)
        # xrandr --output "$DEVICE" --off
        # vlk-xrandr.sh
        ;;
    pointer)
        _normalize_pointer
        ;;
    esac
fi
