#!/usr/bin/env bash

echo "$1 $2 $3"
TYPE="$1"
DEVICE="$2"
STATUS="$3"
shift 3
DESC="$*"


if [[ "$STATUS" == "connected" ]]; then
    echo "xplug detected $TYPE"
    case "$TYPE" in
        display)
            xlayoutdisplay --quiet
            #nitrogen --restore
            vlkbg.sh
        ;;
        pointer)
            #pointer.sh -n
        ;;
    esac
else
    case "$TYPE" in
        display)
            xrandr --output "$DEVICE" --off
        ;;
        pointer)
            pointer.sh -n
        ;;
    esac
fi

