[package]
name = "lsdiff-new"
version = "0.1.0"
edition = "2021"

[dependencies]
lscolors = { version = "0.20.0", default-features = false, features = ["owo-colors"] }
memchr = "2.7.4"
owo-colors = "4.0.0"
