[package]
name = "psa-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", default-features = false, features = ["serde", "clock"] }
clap = "4.4.11"
crossterm = "0.27.0"
eyre = "0.6.11"
lscolors = { version = "0.16.0", default-features = false, features = ["crossterm"] }
nix = { version = "0.27.1", default-features = false, features = ["process", "signal"] }
procfs = { version = "0.16.0", features = ["serde", "chrono"], default-features = false }
ratatui = { version = "0.24.0", features = ["macros", "serde"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
users = "0.11.0"
