[package]
name = "battery"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
futures = "0.3.30"
serde = "1.0.195"
strum = { version = "0.25.0" }
strum_macros = "0.25.3"
tokio = { version = "1.35.1", default-features = false, features = ["tokio-macros", "macros", "rt", "io-std", "io-util", "signal", "fs"] }
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["chrono", "serde", "tracing-serde", "json", "env-filter"] }
zbus = { version = "3.14.1", default-features = false, features = ["tokio"] }
