[package]
name = "battery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
strum = { version = "0.25.0" }
strum_macros = "0.25.3"
tokio = { version = "1.35.1", default-features = false, features = [
    "tokio-macros",
    "macros",
    "rt",
] }
zbus = { version = "3.14.1", default-features = false, features = ["tokio"] }
