[package]
name = "battery"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.77"
blocking = "1.5.1"
clap = { version = "4.4.15", features = ["cargo", "derive", "env", "string"] }
color-eyre = "0.6.2"
futures = "0.3.30"
lazy_static = "1.4.0"
nix = { version = "0.27.1", default-features = false, features = [
    "event",
    "inotify",
    "fs",
] }
parking_lot = { version = "0.12.1", features = ["serde"] }
serde = "1.0.195"
smart-default = "0.7.1"
strum = { version = "0.25.0" }
strum_macros = "0.25.3"
tokio = { version = "1.35.1", default-features = false, features = ["tokio-macros", "macros", "rt", "io-std", "io-util", "signal", "fs", "sync", "process", "parking_lot", "tracing"] }
tracing = { version = "0.1.40", features = ["async-await", "valuable", "release_max_level_off"] }
tracing-subscriber = { version = "0.3.18", features = ["chrono", "serde", "tracing-serde", "json"] }
zbus = { version = "3.14.1", default-features = false, features = ["tokio"] }
zbus-lockstep = "0.3.1"
