[package]
name = "battery_status"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
upower_dbus = "0.3.2"
zbus = { version = "3.10.0", features = ["tokio"] }
